### ISSUE TITLE
No module named 'tensorflow_addons.layers.deformable_conv2d'

### ISSUE THREAD

**Issue by athulvingt** [Ximilar-com/xcenternet#3]

**Comment by liborvaneksw** [comment]
Hi! 
Are you installing the correct TensorFlow Addons? The official branch/package will not work because the deformable conv layer has unfortunately still not been merged. Please see our [readme](https://github.com/Ximilar-com/xcenternet#deformable-convolutions) for more info.

Best regards,
Libor

**Comment by liborvaneksw** [comment]
I'm closing this issue, please let us know if you have more troubles.

**Comment by rodneytai** [comment]
@liborvaneksw Hi! Can you specifically tell us the steps of how to install the tfons package? Your readme file is really unclear. Thank you.

**Comment by liborvaneksw** [comment]
@rodneytai Hi! Unfortunately, the conformable convolutions are still not part of tf addons. Therefore you need to use one of the available forks and install it from source.
- tf2.2: https://github.com/smallsunsun1/addons/tree/feature/deformable_ops#installing-from-source
- tf2.4: https://github.com/Cospel/addons/tree/feature/deformable_ops#installing-from-source

We did not include the instructions here in our readme, because they are available directly in the repositories I've just given you, see "Installing from Source". I hope it will work for you. It's not always easy to build, there are so many versions of the library dependencies out there ...

Do not forget to **replace the repository** in `git clone` with the one you want to build, checkout the proper **branch** and install TensorFlow itself before the build.
